### ISSUE TITLE
Journal::load() would fail, if writing the journal blocks was corrupted

### ISSUE THREAD

**Issue by haraldh** [npmccallum/quoin#1]
E.g. if the underlying device is `quoin-hmac` and the previous push of `0` or `1` was corrupted/interrupted, it would return an error, but since this is only the journal part of the blocks, it can be expected to be corrupted.

https://github.com/npmccallum/quoin/blob/b68c0ba1d27da3d69f0026ed2b927a317409f359/quoin-journal/src/lib.rs#L51-L54

I think you don't want to use `?` here in the above, but only skip the `journal.push()` later.

https://github.com/npmccallum/quoin/blob/b68c0ba1d27da3d69f0026ed2b927a317409f359/quoin-journal/src/lib.rs#L61-L63

**Comment by npmccallum** [comment]
If we can't read the journal, we can no longer determine guarantee that tearing hasn't occurred. Therefore, I think we *must* error here to always enforce our guarantee.

**Comment by haraldh** [comment]
So, there is no recover in case block 0 or 1 is corrupted?

**Comment by npmccallum** [comment]
`quoin-hmac` requires `quoin-journal` underneath it. So stacking them the other way around doesn't make sense. We could maybe make this more explciit.

But in general, I'm not sure what to do here. Here's the scenario I'm imagining:
1. the metadata block is successfully written
2. the journal block is successfully written
3. the real block is torn

In that scenario, if we are unable to read either metadata or journal blocks we cannot recover from tearing and therefore we cannot uphold our tear-free guarantee. I'm open to alternatives.
